/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_tango_JaVaSTyle_JVSTJavaHost */

#ifndef _Included_org_tango_JaVaSTyle_JVSTJavaHost
#define _Included_org_tango_JaVaSTyle_JVSTJavaHost
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tango_JaVaSTyle_JVSTJavaHost
 * Method:    initJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tango_JaVaSTyle_JVSTJavaHost_initJNI
  (JNIEnv *, jclass);

/*
 * Class:     org_tango_JaVaSTyle_JVSTJavaHost
 * Method:    declareHost
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_tango_JaVaSTyle_JVSTJavaHost_declareHost
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
