/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_tango_JaVaSTyle_JVSTLibrary */

#ifndef _Included_org_tango_JaVaSTyle_JVSTLibrary
#define _Included_org_tango_JaVaSTyle_JVSTLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tango_JaVaSTyle_JVSTLibrary
 * Method:    nativeLoadVST
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_tango_JaVaSTyle_JVSTLibrary_nativeLoadVST
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_tango_JaVaSTyle_JVSTLibrary
 * Method:    nativeUnloadVST
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_tango_JaVaSTyle_JVSTLibrary_nativeUnloadVST
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
