/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tango_jniTools_NativePointer */

#ifndef _Included_org_tango_jniTools_NativePointer
#define _Included_org_tango_jniTools_NativePointer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif